SConstruct
browser-test/main.c
prio/rand.c

Have libprio use its own NSS context instead of relying on the global context. This follows the recommendation of https://wiki.mozilla.org/NSS_Library_Init.

Use NSS_InitContext instead of NSS_Init

---

SConstruct
prio/client.c
prio/config.c
prio/config.h
prio/mparray.h
prio/poly.h
prio/prg.h
prio/rand.c
prio/rand.h
prio/serial.c
prio/server.c
prio/share.h
prio/util.h
ptest/client_test.c
ptest/encrypt_test.c
ptest/fft_test.c
ptest/mpi_test.c
ptest/mutest.c
ptest/prg_test.c
ptest/rand_test.c
ptest/serial_test.c
ptest/server_test.c
ptest/share_test.c

Good thing @franziskuskiefer asked me to remove `mpi/` dir when we import - we were still trying to build against the header in libprio, not the one in m-c!
I've tested that this builds fine in mozilla-central if I add the NSS `mpi/` dir to the include path, and libprio also builds fine for me with Scons.

look for mpi header in system path instead of file path

---

prio/encrypt.c

So I am still seeing an NSS assert at shutdown when using Prio in debug builds, I debugged it down to here:
https://searchfox.org/mozilla-central/rev/f2ac80ab7dbde5400a3400d463e07331194dec94/security/nss/lib/pk11wrap/pk11util.c#91
It looks like what's happening is `PK11_GetInternalSlot` is called without a corresponding `PK11_FreeSlot`, which is what this PR does. (`PK11_FreeSlot` returns void which is why there is no error check)
I'm testing on macOS and don't see the assert in my local debug build with this patch, and it also passes the libprio browser-test.

free PK11 slot as this appears to be leaking NSS resources at shutdown

---

.travis.yml
README.md
SConstruct

I'd suggest using Clang as the supported compiler - I know the big open source projects are moving to it on all platforms, and there are a lot of supported static analysis tools.

issue #25 - use clang as the compiler

---

browser-test/encode-once.js

Another silly late-breaking API change - turns out the code using this is all synchronous so making a Promise-based API is counter-productive. Pretty trivial change, but it avoids some terrible JS code in the consumer this way.

per bug 1465251, switch to sync version of PrioEncoder.encode()

---

SConstruct

I want to compile libprio with position independent code (`-fPIC`) to wrap it in a Python library. Setting `CFLAGS='-fPIC' scons` unfortunately doesn't work because the flags are reset in MPI.
https://github.com/mozilla/libprio/blob/02beee180ea3e9b88a45059fd878760c48c187ba/mpi/SConscript#L6
This PR adds a compiler flag that isn't overloaded. According to the [SCons documentation](https://www.scons.org/doc/HTML/scons-user.html#cv-CCFLAGS) and [this user guide](http://pages.cs.wisc.edu/~driscoll/software/scons/variables.html), `CCFLAGS` is a commonly used variable that gets passed to both the C and C++ compiler.

Add CCFLAGS to compiler options

---

README.md
SConstruct

PR #34 changes the way compiler flags are read from the environment, and
SCons seems to want `LINKFLAGS` set in the enviroment instead of
`LDFLAGS` - this was being mapped before.
It's probably not worth re-mapping this, instead just change it so what is
specified in the README still works for platforms that need to install
NSS in a weird place (like macOS and Windows) :)

change readme and SConstruct to specify linkflags not ldflags

---

.travis.yml
SConstruct

Per #44:
* In debug mode, enable clang's AddressSanitizer and UndefinedBehaviorSanitizer.
* Configure Travis to compile in debug mode.
These should catch some memory/C errors in testing.

Use AddressSanitizer and UBSanitizer in ptest

---

SConstruct
pclient/main.c
prio/encrypt.c
prio/poly.c
prio/prg.c
prio/rand.c
prio/serial.c
ptest/client_test.c
ptest/fft_test.c
ptest/prg_test.c
ptest/rand_test.c
ptest/serial_test.c
ptest/server_test.c

This commit removes all stack-allocated VLAs.
Last week, @sadjad convinced me that stack-allocated arrays are dangerous: If an attacker can control the size of the allocated array, the attacker can allocate a huge array on the stack and crash the program using a stack overflow.
I don't think that this is a terribly pressing concern for libprio, but since MSVC doesn't support VLAs anyways, we might as well get rid of them entirely.

Remove all variable-length arrays on the stack

---

prio/encrypt.c

While looking at the code in `encrypt.c`, I noticed that there's a bug that might cause `slot` to never get cleaned up.

Move `PK11_FreeSlot` below `cleanup` label

---

prio/poly.c

This should probably be `MP_CHECKC`. Otherwise this leaks.
(Found by coverity)

memory leak in fft_interpolate_raw

---

.travis.yml
README.md
SConstruct
include/mprio.h
prio/encrypt.c
ptest/client_test.c
ptest/encrypt_test.c
ptest/fft_test.c
ptest/prg_test.c
ptest/rand_test.c
ptest/serial_test.c
ptest/server_test.c
ptest/share_test.c
ptest/test_util.h

* This commit adds import/export functions for private keys to fix #48 .
* Also, while working on this, I realized that having the clang sanitizers on interferes with running valgrind, so I have a commit in here that allows turning the sanitizers on/off independently of `DEBUG` mode.

Functions for import/export of private keys

---

prio/prg.c
prio/prg.h
prio/server.c
ptest/client_test.c
ptest/prg_test.c

**Short version:** This PR fixes a small security bug in libprio. The bug would have taken quite a bit of work to exploit, but is a bug nonetheless.
**Long version:** Per Appendix D.2 of the full version of the Prio paper, the servers should evaluate the polynomials f, g, and h at a random point r in the set {M+1, ..., modulus-1}, where M is the number of multiplication gates in the "Valid" circuit. The implementation previously—and incorrectly—sampled the point r from the larger set {0, ..., modulus-1}.
The probability that a random point r would fall into the "bad set" {0, ..., M} is only (M+1)/(modulus size). Since we are using a 72-bit modulus, this probability would be no more than ~1/2^{60} for the data sizes that libprio currently supports. So, with probability ~1/2^{60}, the …

Fix security bug in proof-checking code

---

README.md
SConstruct

This modifies the build script to include the right paths based on the current operating system (macOS or linux).

Update SConstruct to modify include path based on sys.platform

---

prio/encrypt.c

PRIO_TAG is a fixed-size string, we can use sizeof to the same effect.
This also has the nice side-effect of removing a variable-length-array
since AAD_LEN could not be known at compile-time

remove unnecessary runtime call to strlen()

---

prio/serial.c
prio/util.h

This fixes several checks that jump over the (non-empty) `cleanup` section in `serial_read_packet_client`, as well as a straight return in the switch case.

Fix memory leak in serial_read_packet_client

---

prio/serial.c
ptest/serial_test.c

* In `serial_read_packet_client`, we should check that the type
of the incoming packet matches the type of the `PrioPacketClient`
passed into `serial_read_packet_client` and fail if the two don't
match.
* Add a test for this behavior.

Fix serialization bug in `prio/serial.c`

---

.travis.yml

Regressed by https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=241463.
`/quarterly` (default on releases) package set was refreshed on 2020-07-07.
```
$ pkg search scons
scons-py27-3.1.2               Build tool alternative to make
scons-py37-3.1.2               Build tool alternative to make
```

CI: unbreak FreeBSD

---

prio/client.c
prio/prg.c
prio/prg.h
prio/server.c
ptest/prg_test.c

The servers in Prio use a shared secret to generate common randomness. The servers use this randomness in the protocol they run for checking the well-formedness of client submissions. For security (i.e., to protect against malicious clients) it is important that clients not be able to predict the random values that the servers use.
Currently, `PrioServer_new` takes as input a shared secret. Although it is not specified very clearly in the documentation, it is important that the servers use a _different_ shared secret for every protocol run. Even if we fix the documentation, I suspect that users of the library will reuse the same shared secret over many protocol runs, which could potentially cause problems.
To protect against this failure mode, this PR hashes the `shared_secret` value …

Hash batchID with shared secret to get PRG seed.

---

Dockerfile.dist
docker-compose.yml
python/MANIFEST.in
python/Makefile
python/README.md
python/setup.py
scripts/python-dist.sh

This PR adds the ability to distribute binary wheels for use in macOS and Linux. The `scripts/python-dist.sh` script will generate wheels for supported Python versions and upload them to pypi. The [uploaded package for `prio==1.0.3` can be tested from testpypi](https://test.pypi.org/project/prio/1.0.3/).
```bash
docker run -it python:3 bash
apt update && apt install libmsgpackc2 libnss3
pip3 install -i https://test.pypi.org/simple/ prio==1.0.3
python3 -c "from prio.libprio import *; Prio_init(); print(PrioPRGSeed_randomize())"
```
This should work in most environments where it would be useful to run Prio (e.g. a Dataproc or EMR cluster). There are some caveats here:
* The deployment process is manual. Adding this to CI is doable, but it requires some setup. It is easier to manually push …

Add script to distribute binary wheels

---

include/mprio.h
prio/serial.c
prio/server.c
ptest/serial_test.c
ptest/server_test.c
python/setup.py
python/src/libprio.py
python/swig/libprio.i
python/swig/libprio_wrap.c
python/tests/test_libprio_foldable.py
python/tests/test_libprio_serialize.py

The current interface requires a long-lived pointer to a `PrioServer` structure. This makes it difficult to use the library when server state is distributed across several processes. This PR adds methods for server serialization and deserialization, as well as a method for merging the state of two server structures.

Add interface to serialize and merge server state

---

prio/server.c
ptest/client_test.c

PrioTotalShare_set_data_uint can not use MPArray_copy, which would have overwritten t->data_shares. Instead of overwriting each field of t->data_shares and then adding onto it, it omitted the zeroing. This leads to inaccurate results when reusing memory that has been allocated once and not zeroed between aggregation rounds.
Up till now, the tests reallocated memory for every aggregation round, thus did not detect this error. This PR fixes the omission in PrioTotalShare_set_data_uint and modifies the tests to check over multiple rounds.

Fix and test zeroing of t->data_shares in set_data_uint
